# Generated by Django 5.1.4 on 2026-05-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningsession",
            name="chat_history",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
