# Generated by Django 5.1.4 on 2026-05-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_learningsession_chat_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningsession",
            name="active_quizzes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="learningsession",
            name="quiz_progress",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
